--1.Muestra el nombre de las empresas productoras de Huelva o Málaga ordenadas por el nombre en orden alfabético inverso.
SELECT NOMBRE_EMPRESA
FROM EMPRESAPRODUCTORA
WHERE UPPER(CIUDAD_EMPRESA) LIKE 'HUELVA' 
OR UPPER(CIUDAD_EMPRESA) LIKE 'MALAGA'
ORDER BY NOMBRE_EMPRESA;
--2. Mostrar los nombres de los destinos cuya ciudad contenga una b mayúscula o minúscula.
SELECT NOMBRE_DESTINO
FROM DESTINO
WHERE UPPER(CIUDAD_DESTINO) LIKE '%B%';
--3. Obtener el código de los residuos con una cantidad superior a 4 del constituyente 116.
SELECT COD_RESIDUO
FROM RESIDUO_CONSTITUYENTE
WHERE CANTIDAD > 4
AND COD_CONSTITUYENTE LIKE 116;
--4. Muestra el tipo de transporte, los kilómetros y el coste de los traslados realizados en diciembre de 1994.
SELECT TIPO_TRANSPORTE, KMS, COSTE
FROM TRASLADO
WHERE EXTRACT(MONTH FROM FECHA_ENVIO)= 12
AND EXTRACT(YEAR FROM FECHA_ENVIO)= 1994;
--5. Mostrar el código del residuo y el número de constituyentes de cada residuo.
SELECT COD_RESIDUO, COUNT(COD_CONSTITUYENTE)
FROM RESIDUO_CONSTITUYENTE
GROUP BY COD_RESIDUO;
--6. Mostrar la cantidad media de residuo vertida por las empresas durante el año 1994.
SELECT AVG(nvl(CANTIDAD,0))
FROM RESIDUO_EMPRESA
WHERE EXTRACT(YEAR FROM FECHA)= 1994;
--7. Mostrar el mayor número de kilómetros de un traslado realizado el mes de marzo.
SELECT MAX(KMS)
FROM TRASLADO
WHERE EXTRACT(MONTH FROM FECHA_ENVIO)= 03;
--8. Mostrar el número de constituyentes distintos que genera cada empresa, mostrando también el nif de la empresa,
--para aquellas empresas que generen más de 4 constituyentes.
SELECT COUNT(DISTINCT(COD_CONSTITUYENTE)), RE.NIF_EMPRESA 
FROM RESIDUO_CONSTITUYENTE RC, RESIDUO R, RESIDUO_EMPRESA RE 
WHERE RC.COD_RESIDUO = R.COD_RESIDUO 
AND R.COD_RESIDUO =RE.COD_RESIDUO 
AND RC.CANTIDAD > 4
GROUP BY RE.NIF_EMPRESA;
--9. Mostrar el nombre de las diferentes empresas que han enviado residuos que contenga la palabra metales en 
--su descripción.
SELECT DISTINCT NOMBRE_EMPRESA 
FROM EMPRESAPRODUCTORA
WHERE UPPER(ACTIVIDAD) LIKE '%METALES%';
--10. Mostrar el número de envíos que se han realizado entre cada ciudad, indicando también la ciudad origen y 
--la ciudad destino.
SELECT COUNT(TRASLADO.CANTIDAD) AS NUMENVIOS, EMPRESAPRODUCTORA.CIUDAD_EMPRESA AS CIUDAD_ORIGEN, DESTINO.CIUDAD_DESTINO AS CIUDAD_DESTINO
FROM DESTINO,TRASLADO, EMPRESAPRODUCTORA
WHERE DESTINO.COD_DESTINO = TRASLADO.COD_DESTINO
AND TRASLADO.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
GROUP BY EMPRESAPRODUCTORA.CIUDAD_EMPRESA, DESTINO.CIUDAD_DESTINO;
--11. Mostrar el nombre de la empresa transportista que ha transportado para una empresa que esté en Málaga o en Huelva 
--un residuo que contenga Bario o Lantano. Mostrar también la fecha del transporte.
SELECT EMPRESATRANSPORTISTA.CIUDAD_EMPTRANSPORTE, TRASLADO.FECHA_ENVIO
FROM EMPRESATRANSPORTISTA, TRASLADO, DESTINO, RESIDUO, RESIDUO_CONSTITUYENTE, CONSTITUYENTE, EMPRESAPRODUCTORA
WHERE DESTINO.COD_DESTINO = TRASLADO.COD_DESTINO
AND TRASLADO.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
AND TRASLADO.COD_RESIDUO = RESIDUO.COD_RESIDUO
AND RESIDUO.COD_RESIDUO = RESIDUO_CONSTITUYENTE.COD_RESIDUO
AND RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE = CONSTITUYENTE.COD_CONSTITUYENTE
AND ((UPPER(DESTINO.NOMBRE_DESTINO) LIKE 'MALAGA'
OR UPPER(DESTINO.NOMBRE_DESTINO) LIKE 'HUELVA')
AND (UPPER(NOMBRE_CONSTITUYENTE) LIKE 'BARIO'
OR UPPER(NOMBRE_CONSTITUYENTE) LIKE 'LANTANO'));
--12. Mostrar el coste por kilómetro del total de traslados encargados por la empresa productora Carbonsur.
SELECT TRASLADO.KMS*TRASLADO.COSTE
FROM TRASLADO, EMPRESAPRODUCTORA
WHERE TRASLADO.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
AND UPPER(EMPRESAPRODUCTORA.NOMBRE_EMPRESA) LIKE 'CARBONSUR';
--13. Mostrar el número de constituyentes de cada residuo.
SELECT COUNT(COD_CONSTITUYENTE), COD_RESIDUO
FROM RESIDUO_CONSTITUYENTE
GROUP BY COD_RESIDUO;
--14. Mostrar la descripción de los residuos y la fecha que se generó el residuo, para aquellos residuos que se han 
--generado en los últimos 30 días por una empresa cuyo nombre tenga una c. La consulta debe ser válida para cualquier 
--fecha y el listado debe aparecer ordenado por la descripción del residuo y la fecha.
SELECT RESIDUO.COD_RESIDUO, RESIDUO_EMPRESA.FECHA
FROM RESIDUO, RESIDUO_EMPRESA, EMPRESAPRODUCTORA
WHERE RESIDUO.COD_RESIDUO = RESIDUO_EMPRESA.COD_RESIDUO
AND RESIDUO_EMPRESA.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
AND EXTRACT(DAY FROM RESIDUO_EMPRESA.FECHA)= EXTRACT(DAY FROM sysdate)-30
AND UPPER(EMPRESAPRODUCTORA.NOMBRE_EMPRESA) LIKE '%C%'
ORDER BY RESIDUO.COD_RESIDUO, RESIDUO_EMPRESA.FECHA;
