--Apartado 1
SELECT A.NOMBRE , A.APELLIDOS 
FROM AFICIONADOS A, EJEMPLARESMARIPOSAS E
WHERE E.DNI_CAPTURA= A.DNI
GROUP BY A.NOMBRE ,A.APELLIDOS  
HAVING COUNT(E.NOMBRE_ESPECIE) = (SELECT MAX(COUNT(E.NOMBRE_ESPECIE))
								  FROM EJEMPLARESMARIPOSAS E
								  GROUP BY E.DNI_CAPTURA);
--Apartado 2
SELECT DISTINCT E.NOMBRE_ESPECIE 
FROM EJEMPLARESMARIPOSAS E
WHERE TIPO_EJEMPLAR= ANY(SELECT TIPO_EJEMPLAR
						 FROM EJEMPLARESMARIPOSAS E
						 WHERE E.TIPO_EJEMPLAR IN('L'));
--Apartado 3
SELECT A.*
FROM AFICIONADOS A, COLECCIONES C
WHERE A.DNI =C.DNI 
AND C.PRECIO_ESTIMADO = (SELECT MAX(C.PRECIO_ESTIMADO)
						 FROM COLECCIONES C);
--Apartado 4
SELECT DNI_CAPTURA
FROM EJEMPLARESMARIPOSAS E
WHERE NOMBRE_ESPECIE = ANY(SELECT NOMBRE_ESPECIE
						   FROM EJEMPLARESMARIPOSAS
						   WHERE NOMBRE_ESPECIE IN ('Saturnia Pavonia'));
--Apartado 5
SELECT DISTINCT  G.*, E.NOMBRE_ESPECIE  
FROM GENEROS G, ESPECIES E, EJEMPLARESMARIPOSAS E2
WHERE G.NOMBRE_GENERO = E.NOMBRE_GENERO 
AND E.NOMBRE_ESPECIE =E2.NOMBRE_ESPECIE 
AND E.NOMBRE_ESPECIE NOT IN(SELECT E.NOMBRE_ESPECIE
					    FROM EJEMPLARESMARIPOSAS E);
--Apartado 6
SELECT DISTINCT A.*
FROM AFICIONADOS A, EJEMPLARESMARIPOSAS E, COLECCIONES C
WHERE A.DNI =E.DNI_CAPTURA 
AND A.DNI =C.DNI 
AND A.DNI <> ANY(SELECT C.DNI
				 FROM COLECCIONES c);
--Apartado 7
SELECT G.NOMBRE_FAMILIA 
FROM GENEROS G, ESPECIES E
WHERE G.NOMBRE_GENERO =E.NOMBRE_GENERO 
AND E.NOMBRE_ESPECIE =ANY(SELECT E.NOMBRE_ESPECIE  
						  FROM ESPECIES E
						  WHERE UPPER(E.NOMBRE_ESPECIE) LIKE 'A%')
GROUP BY G.NOMBRE_FAMILIA 
HAVING COUNT(E.NOMBRE_ESPECIE)>5
ORDER BY G.NOMBRE_FAMILIA DESC;
--Apartado 8
SELECT E.NOMBRE_ESPECIE , E.DNI_CAPTURA , E.DNI_CAPTURA 
FROM EJEMPLARESMARIPOSAS E
WHERE TAMANO =(SELECT MIN(TAMANO)
			   FROM EJEMPLARESMARIPOSAS);
--Apartado 9
SELECT DISTINCT E.NOMBRE_CIENTIFICO  
FROM ESPECIES E, EJEMPLARESMARIPOSAS E2
WHERE E.NOMBRE_ESPECIE = E2.NOMBRE_ESPECIE 
AND E2.TAMANO >(SELECT AVG(NVL(E.TAMANO,0))
				FROM EJEMPLARESMARIPOSAS E);
--Apartado 10
SELECT DISTINCT Z.PROVINCIA, Z.NOMBRE_ZONA  
FROM ZONLOCPRO Z, EJEMPLARESMARIPOSAS E
WHERE Z.NOMBRE_ZONA =E.NOMBRE_ZONA 
AND Z.NOMBRE_ZONA NOT IN (SELECT E.NOMBRE_ZONA 
					      FROM EJEMPLARESMARIPOSAS E);
--Apartado 11
SELECT E.SEXO 
FROM EJEMPLARESMARIPOSAS E
GROUP BY E.SEXO 
HAVING COUNT(E.NOMBRE_ESPECIE) = (SELECT MIN(COUNT(E.NOMBRE_ESPECIE))
								  FROM EJEMPLARESMARIPOSAS E
								  GROUP BY E.SEXO);
--Apartado 12
CREATE VIEW NOMBRES
(NOMBRE_COMUN,NOMBRE_CIENTIFICO)
AS
SELECT E.NOMBRE_ESPECIE, E.NOMBRE_CIENTIFICO 
FROM ESPECIES E, EJEMPLARESMARIPOSAS E2
WHERE E.NOMBRE_ESPECIE =E2.NOMBRE_ESPECIE 
AND EXTRACT (YEAR FROM E2.FECHA_CAPTURA) BETWEEN 1996 AND 1997
ORDER BY E2.NOMBRE_ZONA DESC; 

SELECT NOMBRE_COMUN, NOMBRE_CIENTIFICO
FROM NOMBRES;
--Apartado 13
SELECT Z.PROVINCIA , Z.LOCALIDAD 
FROM ZONLOCPRO Z NATURAL JOIN EJEMPLARESMARIPOSAS E 
GROUP BY Z.PROVINCIA , Z.LOCALIDAD 
HAVING COUNT(E.FECHA_CAPTURA)>6
ORDER BY COUNT(E.FECHA_CAPTURA);
